version: '3.7'

networks:
  traefik-public:

services:
  traefik:
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    # A container that exposes an API to show its IP address
    image: containous/whoami
    networks:
      - traefik-public
    labels:
      # Explicitly tell Traefik to expose this container
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      # The domain the service will respond to
      - "traefik.http.routers.whoami.rule=Host(`${WHOAMI_DOMAIN}`)"
      # Use HTTPS
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=cloudflare"
