version: '3.7'

networks:
  traefik-public:

services:
  traefik:
    image: traefik:v2.0
    restart: unless-stopped
    networks:
      - traefik-public
    ports:
      # HTTP & HTTPS
      - '80:80'
      - '443:443'
      # The Web UI (enabled by --api.insecure=true)
      - '127.0.0.1:8080:8080'
    environment:
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
      - TZ=Europe/Zurich
    command:
      - '--global.checkNewVersion=true'
      - '--global.sendAnonymousUsage=false'
      # DOCKER (Dynamic config)
      - '--providers.docker'
      - '--providers.docker.watch=true'
      - '--providers.docker.endpoint=unix:///var/run/docker.sock'
      - '--providers.docker.exposedByDefault=false'
      - '--providers.docker.network=traefik-public'
      - '--providers.docker.swarmMode=false'
      # WEBMIN on localhost (8080)
      - '--api.insecure=true'
      - '--api.dashboard'
      # Listen to incoming HTTP requests (80)
      - '--entryPoints.web.address=:80'
      # Listen to HTTPS (443)
      - '--entryPoints.websecure.address=:443'
      - '--certificatesresolvers.cloudflare.acme.email=${LETSENCRYPT_EMAIL}'
      - '--certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json'
      - '--certificatesresolvers.cloudflare.acme.dnschallenge=true'
      - '--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare'
      # DEBUG
      # - '--log.level=DEBUG'
      # - '--certificatesresolvers.cloudflare.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory'
    labels:
      - "traefik.enable=true"
      # global redirect to https
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.redirects.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirects.entrypoints=web"
      - "traefik.http.routers.redirects.middlewares=redirect-to-https"
      # webmin protected by BasicAuth
      - "traefik.http.middlewares.ask-basic-auth.basicauth.users=${BASIC_AUTH}"
      - "traefik.http.routers.webmin.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.webmin.entrypoints=websecure"
      - "traefik.http.routers.webmin.tls.certresolver=cloudflare"
      - "traefik.http.routers.webmin.service=api@internal"
      - "traefik.http.routers.webmin.middlewares=ask-basic-auth"
