version: '3.7'

networks:
  traefik-public:

services:
  traefik:
    image: traefik:v2.0
    # domainname: ${TRAEFIK_DOMAIN}
    restart: unless-stopped
    ports:
      # - '443:443'
      - '80:80'
      # The Web UI (enabled by --api.insecure=true)
      - '8080:8080'
    networks:
      - traefik-public
    # labels:
    #   - "traefik.enable=true"
    #   # middlewares
    #   - "traefik.http.middlewares.testHeader.headers.framedeny=true"
    #   - "traefik.http.middlewares.testHeader.headers.sslredirect=true"
    #   - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    #   - "traefik.http.middlewares.auth.basicauth.users=test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/"
    #   # web
    #   - "traefik.http.routers.traefik.entrypoints=web"
    #   - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_WEBMIN}`)"
    #   # - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    #   # web secure
    #   - "traefik.http.routers.traefik_https.entrypoints=web-secure"
    #   - "traefik.http.routers.traefik_https.rule=Host(`${TRAEFIK_WEBMIN}`)"
    #   - "traefik.http.routers.traefik_https.tls=true"
    #   - "traefik.http.routers.traefik_https.tls.certresolver=basic"
    #   # - "traefik.http.routers.traefik_https.service=api@internal"
    #   # - "traefik.http.routers.traefik_https.tls.domains[0].main=*.${TRAEFIK_DOMAIN}"
    #   # - "traefik.http.routers.traefik_https.tls.domains[0].sans=${TRAEFIK_DOMAIN}"
    #   # - "traefik.http.routers.traefik_https.middlewares=auth"
    #   # global redirect to https
    #   - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
    #   - "traefik.http.routers.redirs.entrypoints=web"
    #   - "traefik.http.routers.redirs.middlewares=redirect-to-https"
