version: '3.7'

volumes:
  pmcconfig:

services:
  memcached:
    image: memcached
    container_name: memcached
    restart: always

  phpmemcachedadmin:
    image: jacksoncage/phpmemcachedadmin
    restart: always
    depends_on:
      - memcached
    volumes:
      - pmcconfig:/phpmemcachedadmin
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${TRAEFIK_PUBLIC_NETWORK}"
      - "traefik.http.middlewares.cacheadmin-stripprefix.stripprefix.prefixes=${PHPMEMCACHEDADMIN_PATH}"
      - "traefik.http.routers.phpmemcachedadmin.entrypoints=websecure"
      - "traefik.http.routers.phpmemcachedadmin.tls.certresolver=dns-ovh"
      - "traefik.http.routers.phpmemcachedadmin.middlewares=ask-basic-auth"
      - "traefik.http.routers.phpmemcachedadmin.middlewares=cacheadmin-stripprefix"
      - "traefik.http.routers.phpmemcachedadmin.rule=Host(`${PHPMEMCACHEDADMIN_DOMAIN}`) && PathPrefix(`${PHPMEMCACHEDADMIN_PATH}`)"
