version: '3.5'

networks:
  traefik-public:

services:

  nginx-entrypoint:
    image: nginx
    container_name: nginx-entrypoint
    restart: always
    ports:
      - "80:80"
    networks:
      - traefik-public
    volumes:
       - $PWD/etc/nginx.conf:/etc/nginx/nginx.conf
       - $PWD/etc/proxy.conf:/etc/nginx/proxy.conf
       - $PWD/etc/conf.d:/etc/nginx/conf.d

  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    command: --docker --docker.exposedbydefault=false --logLevel=INFO
    ports:
      - "443:443"
      - "8081:8081"
    networks:
      - traefik-public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/etc/traefik.toml:/etc/traefik/traefik.toml
      - $PWD/acme:/etc/traefik/acme
