version: '3.7'

volumes:
  pmcconfig:

services:
  memcached:
    image: memcached
    restart: always

  phpmemcachedadmin:
    image: jacksoncage/phpmemcachedadmin
    restart: always
    depends_on:
      - memcached
    volumes:
      - pmcconfig:/phpmemcachedadmin
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${TRAEFIK_PUBLIC_NETWORK}"
      - "traefik.http.routers.phpmemcachedadmin.entrypoints=websecure"
      - "traefik.http.routers.phpmemcachedadmin.tls.certresolver=dnsresolver"
      - "traefik.http.routers.phpmemcachedadmin.rule=Host:${PHPMEMCACHEDADMIN_DOMAIN};PathPrefixStrip:/${PHPMEMCACHEDADMIN_PATH}"
