version: '3.7'

networks:
  default:
    external:
      name: traefik-public

services:
  traefik:
    image: traefik:v2.0
    restart: unless-stopped
    networks:
      - traefik-public
    ports:
      # HTTP & HTTPS
      - '80:80'
      - '443:443'
      # The Web UI (enabled by --api.insecure=true)
      - '127.0.0.1:8080:8080'
      # Other services
      - '${SSH_PORT}:22'
      - '${PG_PORT}:5432'
    environment:
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
      - TZ=Europe/Zurich
    command:
      - '--global.checkNewVersion=true'
      - '--global.sendAnonymousUsage=false'
      # DOCKER (Dynamic config)
      - '--providers.docker'
      - '--providers.docker.watch=true'
      - '--providers.docker.endpoint=unix:///var/run/docker.sock'
      - '--providers.docker.exposedByDefault=false'
      - '--providers.docker.network=traefik-public'
      - '--providers.docker.swarmMode=false'
      # WEBMIN on localhost (8080)
      - '--api.insecure=true'
      - '--api.dashboard'
      # Listen to incoming HTTP requests (80)
      - '--entryPoints.web.address=:80'
      # Listen to HTTPS (443)
      - '--entryPoints.websecure.address=:443'
      - '--certificatesresolvers.cloudflare.acme.email=${LETSENCRYPT_EMAIL}'
      - '--certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json'
      - '--certificatesresolvers.cloudflare.acme.dnschallenge=true'
      - '--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare'
      # Listen to other services
      - '--entryPoints.ssh.address=:22'
      - '--entryPoints.pg.address=:5432'
      # DEBUG
      # - '--log.level=DEBUG'
      # - '--certificatesresolvers.cloudflare.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory'
