version: '3.7'

services:

  traefik:
    command:
      - '--global.sendAnonymousUsage=false'
      # DOCKER (Dynamic config)
      - '--providers.docker'
      - '--providers.docker.watch=true'
      - '--providers.docker.endpoint=unix:///var/run/docker.sock'
      - '--providers.docker.exposedByDefault=false'
      - '--providers.docker.network=traefik-public'
      - '--providers.docker.swarmMode=true'
      # Listen to incoming HTTP requests (80)
      - '--entryPoints.web.address=:80'
      # Listen to HTTPS (443)
      - '--entryPoints.websecure.address=:443'
      - '--certificatesresolvers.cloudflare.acme.email=${LETSENCRYPT_EMAIL}'
      - '--certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json'
      - '--certificatesresolvers.cloudflare.acme.dnschallenge=true'
      - '--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare'
