version: '3.7'

services:
  traefik:
    image: traefik:v2.3
    restart: unless-stopped
    ports:
      # HTTP & HTTPS
      - '80:80'
      - '443:443'
      # Other services
      # - '${SSH_PORT}:22'
      # - '${PG_PORT}:5432'
    environment:
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
      - INFOMANIAK_ACCESS_TOKEN=${INFOMANIAK_ACCESS_TOKEN}
      - OVH_ENDPOINT=${OVH_ENDPOINT}
      - OVH_APPLICATION_KEY=${OVH_APPLICATION_KEY}
      - OVH_APPLICATION_SECRET=${OVH_APPLICATION_SECRET}
      - OVH_CONSUMER_KEY=${OVH_CONSUMER_KEY}
      - TZ=Europe/Zurich
    command:
      - '--global.checkNewVersion=true'
      - '--global.sendAnonymousUsage=false'

      # DOCKER (Dynamic config)
      - '--providers.docker'
      - '--providers.docker.watch=true'
      - '--providers.docker.endpoint=unix:///var/run/docker.sock'
      - '--providers.docker.exposedByDefault=false'
      - '--providers.docker.network=${TRAEFIK_PUBLIC_NETWORK}'
      - '--providers.docker.swarmMode=false'

      # Listen to incoming HTTP requests (80)
      - '--entryPoints.web.address=:80'
      # Listen to HTTPS (443)
      - '--entryPoints.websecure.address=:443'

      # Set HTTP challenge
      - '--certificatesResolvers.httpresolver.acme.email=${LETSENCRYPT_EMAIL}'
      - '--certificatesResolvers.httpresolver.acme.storage=/letsencrypt/acme-http.json'
      - '--certificatesResolvers.httpresolver.acme.httpChallenge=true'
      - '--certificatesResolvers.httpresolver.acme.httpChallenge.entryPoint=web'

      # Set DNS challenges
      - '--certificatesresolvers.dns-cloudflare.acme.email=${LETSENCRYPT_EMAIL}'
      - '--certificatesresolvers.dns-cloudflare.acme.storage=/letsencrypt/acme-cloudflare.json'
      - '--certificatesresolvers.dns-cloudflare.acme.dnschallenge=true'
      - '--certificatesresolvers.dns-cloudflare.acme.dnschallenge.provider=cloudflare'

      - '--certificatesresolvers.dns-infomaniak.acme.email=${LETSENCRYPT_EMAIL}'
      - '--certificatesresolvers.dns-infomaniak.acme.storage=/letsencrypt/acme-infomaniak.json'
      - '--certificatesresolvers.dns-infomaniak.acme.dnschallenge=true'
      - '--certificatesresolvers.dns-infomaniak.acme.dnschallenge.provider=infomaniak'

      - '--certificatesresolvers.dns-ovh.acme.email=${LETSENCRYPT_EMAIL}'
      - '--certificatesresolvers.dns-ovh.acme.storage=/letsencrypt/acme.json'
      - '--certificatesresolvers.dns-ovh.acme.dnschallenge=true'
      - '--certificatesresolvers.dns-ovh.acme.dnschallenge.provider=ovh'

      # Listen to other services
      # - '--entryPoints.ssh.address=:22'
      # - '--entryPoints.pg.address=:5432'

      # WEBMIN
      - '--api.dashboard'

      # DEBUG
      - '--log.level=INFO'
      # - '--certificatesresolvers.dnsresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory'
