version: '3.7'

volumes:
  db_data:
  webmin_sessions:

services:
  db:
    image: mariadb:latest
    container_name: db-shared
    restart: always
    env_file:
      - ./etc/db.env
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    env_file:
      - ./etc/db.env
    volumes:
       - webmin_sessions:/sessions
    environment:
      - PMA_ABSOLUTE_URI=${DEFAULT_PROTOCOL}://${PHPMYADMIN_DOMAIN}${PHPMYADMIN_PATH}/
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${TRAEFIK_PUBLIC_NETWORK}"
      - "traefik.http.middlewares.admin-stripprefix.stripprefix.prefixes=${PHPMYADMIN_PATH}"
      - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin.tls.certresolver=dnsresolver"
      - "traefik.http.routers.phpmyadmin.middlewares=admin-stripprefix"
      - "traefik.http.routers.phpmyadmin.rule=Host(`${PHPMYADMIN_DOMAIN}`) && PathPrefix(`${PHPMYADMIN_PATH}`)"
