version: '3.5'

networks:
  cci_frontend:
    external: true
  cci_backend:
    external: true

# volumes:
#   db_data:
#     external: true
#   pmcconfig:
#     external: true

services:

  nginx-entrypoint:
    image: nginx
    container_name: nginx-entrypoint
    restart: always
    ports:
      - "80:80"
    networks:
      - cci_frontend
      - cci_backend
    volumes:
       - $PWD/etc/nginx.conf:/etc/nginx/nginx.conf
       - $PWD/etc/proxy.conf:/etc/nginx/proxy.conf
       - $PWD/etc/conf.d:/etc/nginx/conf.d

  nginx-redirect:
    image: nginx
    container_name: nginx-redirect
    restart: always
    networks:
      - cci_frontend
      - cci_backend
    labels:
        - "traefik.enable=true"
        - "traefik.backend=frontendapp"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.frontend.entryPoints=https"
        - "traefik.frontend.rule=Host:api.cortexia.ch,web.cortexia.ch"
    volumes:
       - $PWD/etc/nginx.conf:/etc/nginx/nginx.conf
       - $PWD/etc/proxy.conf:/etc/nginx/proxy.conf
       - $PWD/etc/conf.d/001-redirect-legacy.conf:/etc/nginx/conf.d/001-redirect-legacy.conf

  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    command: --docker --docker.exposedbydefault=false --logLevel=INFO
    ports:
      - "443:443"
      - "8081:8081"
    networks:
      - cci_frontend
      - cci_backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/etc/traefik.toml:/etc/traefik/traefik.toml
      - $PWD/acme:/etc/traefik/acme

  # db-shared:
  #   image: mariadb:latest
  #   container_name: db-shared
  #   restart: always
  #   networks:
  #     - cci_backend
  #   env_file:
  #     - $PWD/etc/db.env
  #   volumes:
  #      - db_data:/var/lib/mysql

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin
  #   restart: always
  #   networks:
  #     - cci_backend
  #   depends_on:
  #     - db-shared
  #   links:
  #     - db-shared:db
  #   env_file:
  #     - ./etc/db.env
  #   environment:
  #     - PMA_ABSOLUTE_URI=${DEFAULT_PROTOCOL}://${PHPMYADMIN_DOMAIN}/${PHPMYADMIN_PATH}/
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.backend=phpmyadmin"
  #     - "traefik.frontend.passHostHeader=true"
  #     - "traefik.frontend.entryPoints=${DEFAULT_PROTOCOL}"
  #     - "traefik.frontend.rule=Host:${PHPMYADMIN_DOMAIN};PathPrefixStrip:/${PHPMYADMIN_PATH}"

  # memcached:
  #   image: memcached
  #   container_name: memcached
  #   restart: always

  # phpmemcachedadmin:
  #   image: jacksoncage/phpmemcachedadmin
  #   container_name: phpmemcachedadmin
  #   restart: always
  #   depends_on:
  #     - memcached
  #   volumes:
  #     - pmcconfig:/phpmemcachedadmin
  #   expose:
  #     - 80
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.backend=phpmemcachedadmin"
  #     - "traefik.frontend.entryPoints=httpBA"
  #     - "traefik.frontend.rule=Host:${PHPMEMCACHEDADMIN_DOMAIN};PathPrefixStrip:/phpmemcachedadmin"
